#! /opt/homebrew/bin/bash

selected=$(fzf --multi)

comma_separated=$(echo "$selected" | paste -sd "," -)

repomix --include "$comma_separated"

cat repomix-output.txt | pbcopy
rm repomix-output.txt

echo "Copied to clipboard!"

